os: linux
language: php

## Cache composer downloads.
cache:
  directories:
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

php:
- 8.0
- 7.4
- 7.3
- 7.2
- 7.1

jobs:
  fast_finish: true
  include:
    - php: 7.0
      dist: xenial
    - php: 5.6
      dist: xenial
    - php: 5.5
      dist: trusty
    - php: 5.4
      dist: trusty
    - php: 5.3
      dist: precise

before_install:
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

install:
- if [[ $TRAVIS_PHP_VERSION == "5.3" ]]; then phpenv local 5.3.29; fi
# Remove "dev" packages which will not install on PHP 5.3.
- |
  if [[ $TRAVIS_PHP_VERSION == "5.3" ]]; then
    travis_retry composer remove --dev --no-update --no-scripts yoast/yoastcs
    travis_retry composer require --dev --no-update --no-scripts php-parallel-lint/php-parallel-lint
  fi
- travis_retry composer install --no-interaction
- if [[ $TRAVIS_PHP_VERSION == "5.3" ]]; then phpenv local --unset; fi

script:
- echo $TRAVIS_PHP_VERSION
- composer lint
- ./vendor/bin/phpunit
