language: php
dist: trusty

## Cache composer downloads.
cache:
  directories:
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

php:
- 7.2
- 7.1
- 7.0
- 5.6
- 5.5
- 5.4
- "7.4snapshot"

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: PHPCS=1
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise

  allow_failures:
    # Allow failures for unstable builds.
    - php: "7.4snapshot"

before_install:
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

install:
- if [[ $TRAVIS_PHP_VERSION == "5.2" || $TRAVIS_PHP_VERSION == "5.3" ]]; then phpenv local 5.3.29; fi
- if [[ $TRAVIS_PHP_VERSION == "5.2" || $TRAVIS_PHP_VERSION == "5.3" ]]; then composer remove --dev yoast/yoastcs dealerdirect/phpcodesniffer-composer-installer; fi
- if [[ $TRAVIS_PHP_VERSION == "5.2" ]]; then composer remove --dev phpunit/phpunit; fi
- composer install --prefer-dist --no-interaction
- if [[ $TRAVIS_PHP_VERSION == "5.2" || $TRAVIS_PHP_VERSION == "5.3" ]]; then phpenv local --unset; fi

script:
- echo $TRAVIS_PHP_VERSION
- find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
- if [[ "$TRAVIS_PHP_VERSION" == "5.2" ]]; then phpunit; else ./vendor/bin/phpunit; fi
- if [[ "$TRAVIS_PHP_VERSION" != "5.2" ]]; then composer validate --no-check-all; fi
- if [[ $PHPCS == "1" ]]; then vendor/bin/phpcs; fi
