os: linux
language: php

## Cache composer downloads.
cache:
  directories:
    - .cache
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

php:
- 8.0
- 7.3
- 7.2
- 7.1
- "nightly"

jobs:
  fast_finish: true
  include:
    - php: 7.4
      env: PHPCS=1
    - php: 7.0
      dist: xenial
    - php: 5.6
      dist: xenial
    - php: 5.5
      dist: trusty
    - php: 5.4
      dist: trusty
    - php: 5.3
      dist: precise

  allow_failures:
    # Allow failures for unstable builds.
    - php: "nightly"

before_install:
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

install:
- if [[ $TRAVIS_PHP_VERSION == "5.3" ]]; then phpenv local 5.3.29; fi
# Remove "dev" packages which will not install on PHP 5.3.
- |
  if [[ $TRAVIS_PHP_VERSION == "5.3" ]]; then
    travis_retry composer remove --dev --no-update --no-scripts php-parallel-lint/php-console-highlighter yoast/yoastcs
  fi
# Remove "dev" packages which will not install/are not needed on PHP 8.0/nightly.
- travis_retry composer install --no-interaction
- if [[ $TRAVIS_PHP_VERSION == "5.3" ]]; then phpenv local --unset; fi

script:
- echo $TRAVIS_PHP_VERSION
- composer lint
- ./vendor/bin/phpunit
- if [[ "$TRAVIS_PHP_VERSION" == "5.3" || "$TRAVIS_PHP_VERSION" == "7.4" ]]; then composer validate --no-check-all; fi
- if [[ $PHPCS == "1" ]]; then composer check-cs; fi
