name: CS

on:
  # Run on all relevant pushes and on all relevant pull requests.
  push:
    paths-ignore:
      - '**.md'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'phpunit.xml.dist'
      - '.github/dependabot.yml'
      - '.github/workflows/test.yml'
      - 'images/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'phpunit.xml.dist'
      - '.github/dependabot.yml'
      - '.github/workflows/test.yml'
      - 'images/**'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkcs:
    name: 'Check code style'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: cs2pr

      # Validate the composer.json file.
      # @link https://getcomposer.org/doc/03-cli.md#validate
      - name: Validate Composer installation
        run: composer validate --no-check-all

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-php-dependencies-with-composer
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      # Check the codestyle of the files.
      # The results of the CS check will be shown inline in the PR via the CS2PR tool.
      # @link https://github.com/staabm/annotate-pull-request-from-checkstyle/
      - name: Check PHP code style
        id: phpcs
        run: composer check-cs -- --no-cache --report-full --report-checkstyle=./phpcs-report.xml

      - name: Show PHPCS results in PR
        if: ${{ always() && steps.phpcs.outcome == 'failure' }}
        run: cs2pr ./phpcs-report.xml
